### TRY OUT PANDAS USING THE SAMPLE_EMPLOYEE_DATA.CSV: 

#### TASK_1: Load and Explore the Data 

In [248]:
'''Creating a dataframe called df and loading a csv file into the dataframe'''

import pandas as pd
df = pd.read_csv('sample_employee_data.csv')

In [249]:
'''first few rows'''
display(df.head(2))

'''last few rows'''
display(df.tail(2))

ID   Name   Age Department   Salary    JoinDate Gender
0  101  Alice  25.0         HR  50000.0  2020-01-15      F
1  102    Bob  30.0         IT  60000.0  2019-08-01      M

ID   Name   Age Department   Salary    JoinDate Gender
4  105    Eve  29.0         IT      NaN  2020-03-30      F
5  106  Frank  40.0         HR  62000.0  2018-12-05      M

In [250]:
'''The first number in the tuple is the number of rows while the second is the number of columns'''
print(df.shape)

(6, 7)


In [251]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'Department', 'Salary', 'JoinDate', 'Gender'], dtype='object')


In [252]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          6 non-null      int64  
 1   Name        6 non-null      object 
 2   Age         5 non-null      float64
 3   Department  5 non-null      object 
 4   Salary      5 non-null      float64
 5   JoinDate    6 non-null      object 
 6   Gender      6 non-null      object 
dtypes: float64(2), int64(1), object(4)
memory usage: 468.0+ bytes
None


### TASK_2: Generate Summary Statistics 

In [253]:
import numpy as np
STA_summary = np.floor(df[['Age','Salary']].describe())
print(STA_summary)

        Age   Salary
count   5.0      5.0
mean   29.0  55800.0
std     6.0   5118.0
min    22.0  50000.0
25%    25.0  52000.0
50%    29.0  55000.0
75%    30.0  60000.0
max    40.0  62000.0


##### Age column:
  - The average age is 5.0
  - The number of non missing ages is 5.0.
  - Standard Deviation Value explains how far(spread out) other ages are from the average age.
  - The lowest age is 22.0
  - The Q1(first quartile) is 25.0 meaning 25% of the ages in the dataset are lower than 25.0
  - The Q2 (median) is 29.0 meaning 50% of the ages in the dataset are lower than 29.0
  - The Q3(third quartile) is 30.0 meaning 75% of the ages in the dataset are lower than 30.0
  - The highest age is 40.0

##### Salary Column:
- The average salary is 55800.0
- The number of non missing salaries is 5.0
- The Standard Deviation value explain how spread out other salaries are from the average Salary.
- The lowest salary is 50000.0
- TThe Q1(first quartile) is 52000.0 meaning 25% of the salaries in the dataset are lower than 52000.0
- The Q2 (median) is 55000.0 meaning 50% of the salaries in the dataset are lower than 55000.0
- The Q3(third quartile) is 60000.0 meaning 75% of the salaries in the dataset are lower than 60000.0
- The highest salary 62000.0

### TASK_3: Handle Missing Values 

In [254]:
'''rows with boolean value True are missing values'''
display(df.isnull())

ID   Name    Age  Department  Salary  JoinDate  Gender
0  False  False  False       False   False     False   False
1  False  False  False       False   False     False   False
2  False  False   True       False   False     False   False
3  False  False  False        True   False     False   False
4  False  False  False       False    True     False   False
5  False  False  False       False   False     False   False

In [255]:
'''Dropping rows with missing values'''
display(df.dropna())

'''Dropping columns with missing values'''
display(df.dropna(axis  =1))

ID   Name   Age Department   Salary    JoinDate Gender
0  101  Alice  25.0         HR  50000.0  2020-01-15      F
1  102    Bob  30.0         IT  60000.0  2019-08-01      M
5  106  Frank  40.0         HR  62000.0  2018-12-05      M

ID     Name    JoinDate Gender
0  101    Alice  2020-01-15      F
1  102      Bob  2019-08-01      M
2  103  Charlie  2021-06-23      M
3  104    David  2022-11-11      M
4  105      Eve  2020-03-30      F
5  106    Frank  2018-12-05      M

In [256]:
'''The original dataFrame is manipulated if the inplace attribute is set to True'''
df.fillna({'Salary': df['Salary'].mean(), 'Age': df['Age'].mean(), 'Department': 'IT'}, inplace =True)
display(df)

ID     Name   Age Department   Salary    JoinDate Gender
0  101    Alice  25.0         HR  50000.0  2020-01-15      F
1  102      Bob  30.0         IT  60000.0  2019-08-01      M
2  103  Charlie  29.2    Finance  55000.0  2021-06-23      M
3  104    David  22.0         IT  52000.0  2022-11-11      M
4  105      Eve  29.0         IT  55800.0  2020-03-30      F
5  106    Frank  40.0         HR  62000.0  2018-12-05      M

### TASK_4: Data Transformation 

In [257]:
df['JoinDate'] = pd.to_datetime(df['JoinDate'])

'''chceking the datatype of the columns'''
print(df.dtypes)

ID                     int64
Name                  object
Age                  float64
Department            object
Salary               float64
JoinDate      datetime64[ns]
Gender                object
dtype: object


In [258]:
df.rename(columns = {'ID':'Identification Number','Name':'Staff Name','Age':'Staff Age','Salary':'Staff Salary'},inplace =True)
display(df)

Identification Number Staff Name  Staff Age Department  Staff Salary  \
0                    101      Alice       25.0         HR       50000.0   
1                    102        Bob       30.0         IT       60000.0   
2                    103    Charlie       29.2    Finance       55000.0   
3                    104      David       22.0         IT       52000.0   
4                    105        Eve       29.0         IT       55800.0   
5                    106      Frank       40.0         HR       62000.0   

    JoinDate Gender  
0 2020-01-15      F  
1 2019-08-01      M  
2 2021-06-23      M  
3 2022-11-11      M  
4 2020-03-30      F  
5 2018-12-05      M

In [259]:
df = df.astype({'Staff Age': 'int64', 'Staff Salary': 'int64'})
print(df.dtypes)

Identification Number             int64
Staff Name                       object
Staff Age                         int64
Department                       object
Staff Salary                      int64
JoinDate                 datetime64[ns]
Gender                           object
dtype: object


### TASK_5: Sort and Filter the Data

In [260]:
sorted_df = df.sort_values(by = ['Staff Age'])
display(sorted_df)

Identification Number Staff Name  Staff Age Department  Staff Salary  \
3                    104      David         22         IT         52000   
0                    101      Alice         25         HR         50000   
2                    103    Charlie         29    Finance         55000   
4                    105        Eve         29         IT         55800   
1                    102        Bob         30         IT         60000   
5                    106      Frank         40         HR         62000   

    JoinDate Gender  
3 2022-11-11      M  
0 2020-01-15      F  
2 2021-06-23      M  
4 2020-03-30      F  
1 2019-08-01      M  
5 2018-12-05      M

In [261]:
display(df[df['Department'] == 'IT'])

Identification Number Staff Name  Staff Age Department  Staff Salary  \
1                    102        Bob         30         IT         60000   
3                    104      David         22         IT         52000   
4                    105        Eve         29         IT         55800   

    JoinDate Gender  
1 2019-08-01      M  
3 2022-11-11      M  
4 2020-03-30      F

### TASK_6: Group and Aggregate Data 

In [262]:
grouped = df.pivot_table( index =['Department'], values = ['Staff Salary'], aggfunc = 'mean')
display(grouped.astype(int))

Staff Salary
Department              
Finance            55000
HR                 56000
IT                 55933

Apply multiple aggregate functions (mean, median, max) on grouped data.

In [263]:
display(df.pivot_table(index = ['Department'], 
                       values = ['Staff Salary', 'Staff Age'], 
                       aggfunc = ['mean','median','max']))

mean                  median                    max  \
           Staff Age  Staff Salary Staff Age Staff Salary Staff Age   
Department                                                            
Finance         29.0  55000.000000      29.0      55000.0        29   
HR              32.5  56000.000000      32.5      56000.0        40   
IT              27.0  55933.333333      29.0      55800.0        30   

                         
           Staff Salary  
Department               
Finance           55000  
HR                62000  
IT                60000

### TASK_7:  Use Apply, Map, and Lambda Functions 

Create a new column by applying a function to another column. 

In [264]:
'''Creating a NET SALARY column and a TAx column'''
'''Net Salary is the salary that each staff takes home after deducting the tax'''
df['Tax'] = df['Staff Salary'].apply(lambda x: x*0.1).astype(int) #10% tax
df['Net Salary'] = df['Staff Salary'] - df['Tax'].astype(int)
display(df)

Identification Number Staff Name  Staff Age Department  Staff Salary  \
0                    101      Alice         25         HR         50000   
1                    102        Bob         30         IT         60000   
2                    103    Charlie         29    Finance         55000   
3                    104      David         22         IT         52000   
4                    105        Eve         29         IT         55800   
5                    106      Frank         40         HR         62000   

    JoinDate Gender   Tax  Net Salary  
0 2020-01-15      F  5000       45000  
1 2019-08-01      M  6000       54000  
2 2021-06-23      M  5500       49500  
3 2022-11-11      M  5200       46800  
4 2020-03-30      F  5580       50220  
5 2018-12-05      M  6200       55800

Replace values in a column using a mapping dictionary. 

In [265]:
mapping_dict = {'F': 'Female','M': 'Male'}
df['Gender'] = df['Gender'].map(mapping_dict)
display(df)

Identification Number Staff Name  Staff Age Department  Staff Salary  \
0                    101      Alice         25         HR         50000   
1                    102        Bob         30         IT         60000   
2                    103    Charlie         29    Finance         55000   
3                    104      David         22         IT         52000   
4                    105        Eve         29         IT         55800   
5                    106      Frank         40         HR         62000   

    JoinDate  Gender   Tax  Net Salary  
0 2020-01-15  Female  5000       45000  
1 2019-08-01    Male  6000       54000  
2 2021-06-23    Male  5500       49500  
3 2022-11-11    Male  5200       46800  
4 2020-03-30  Female  5580       50220  
5 2018-12-05    Male  6200       55800

### TASK_8: Merge and Concatenate 

In [266]:
dp_location = {'Department': ['IT','HR','Finance'],
              'Location': ['Nairobi, Kenya','Lagos, Nigeria','South Africa']} 
dp_df = pd.DataFrame(dp_location)
display(dp_df)

Department        Location
0         IT  Nairobi, Kenya
1         HR  Lagos, Nigeria
2    Finance    South Africa

In [267]:
merged_df = pd.merge(df,dp_df,  on = 'Department')
display(merged_df)

Identification Number Staff Name  Staff Age Department  Staff Salary  \
0                    101      Alice         25         HR         50000   
1                    102        Bob         30         IT         60000   
2                    103    Charlie         29    Finance         55000   
3                    104      David         22         IT         52000   
4                    105        Eve         29         IT         55800   
5                    106      Frank         40         HR         62000   

    JoinDate  Gender   Tax  Net Salary        Location  
0 2020-01-15  Female  5000       45000  Lagos, Nigeria  
1 2019-08-01    Male  6000       54000  Nairobi, Kenya  
2 2021-06-23    Male  5500       49500    South Africa  
3 2022-11-11    Male  5200       46800  Nairobi, Kenya  
4 2020-03-30  Female  5580       50220  Nairobi, Kenya  
5 2018-12-05    Male  6200       55800  Lagos, Nigeria

In [268]:
'''Concatenating 2 Dataframes'''
pd.concat([df,df], keys = ['First df', 'Second df'])

Identification Number Staff Name  Staff Age Department  \
First df  0                    101      Alice         25         HR   
          1                    102        Bob         30         IT   
          2                    103    Charlie         29    Finance   
          3                    104      David         22         IT   
          4                    105        Eve         29         IT   
          5                    106      Frank         40         HR   
Second df 0                    101      Alice         25         HR   
          1                    102        Bob         30         IT   
          2                    103    Charlie         29    Finance   
          3                    104      David         22         IT   
          4                    105        Eve         29         IT   
          5                    106      Frank         40         HR   

             Staff Salary   JoinDate  Gender   Tax  Net Salary  
First df  0         50000 2020-01-15  Female  5000       45000  
          1         60000 2019-08-01    Male  6000       54000  
          2         55000 2021-06-23    Male  5500       49500  
          3         52000 2022-11-11    Male  5200       46800  
          4         55800 2020-03-30  Female  5580       50220  
          5         62000 2018-12-05    Male  6200       55800  
Second df 0         50000 2020-01-15  Female  5000       45000  
          1         60000 2019-08-01    Male  6000       54000  
          2         55000 2021-06-23    Male  5500       49500  
          3         52000 2022-11-11    Male  5200       46800  
          4         55800 2020-03-30  Female  5580       50220  
          5         62000 2018-12-05    Male  6200       55800

### TASK_9:  Pivot and Reshape

In [269]:
cleaned_df = merged_df

In [270]:
'''A pivot table that displays the total salary and total tax of each department'''

total_salary = cleaned_df.pivot_table(index = ['Department'], values = ['Net Salary', 'Tax'], aggfunc ='sum')
display(total_salary)

Net Salary    Tax
Department                   
Finance          49500   5500
HR              100800  11200
IT              151020  16780

In [271]:
'''A pivot table that displays the average Net salary by Location'''
display(merged_df.pivot_table(index =['Location'], values =['Net Salary'], aggfunc = 'mean' ).astype(int))

Net Salary
Location                  
Lagos, Nigeria       50400
Nairobi, Kenya       50340
South Africa         49500

In [272]:
'''A pivot table that counts the number of staff by Department and Gender'''
display(merged_df.pivot_table(index = ['Department','Gender'] , values = ['Identification Number'], aggfunc = 'count'))

Identification Number
Department Gender                       
Finance    Male                        1
HR         Female                      1
           Male                        1
IT         Female                      1
           Male                        2

Reshape the dataset using melt to go from wide to long format. 

In [273]:
'''Melting the salary-related columns'''
melted_df = pd.melt(merged_df, id_vars =['Staff Name','Department'], value_vars = ['Staff Salary', 'Net Salary','Tax'],
                   var_name = 'Salary Component', value_name = "Amount")
display(melted_df)

Staff Name Department Salary Component  Amount
0       Alice         HR     Staff Salary   50000
1         Bob         IT     Staff Salary   60000
2     Charlie    Finance     Staff Salary   55000
3       David         IT     Staff Salary   52000
4         Eve         IT     Staff Salary   55800
5       Frank         HR     Staff Salary   62000
6       Alice         HR       Net Salary   45000
7         Bob         IT       Net Salary   54000
8     Charlie    Finance       Net Salary   49500
9       David         IT       Net Salary   46800
10        Eve         IT       Net Salary   50220
11      Frank         HR       Net Salary   55800
12      Alice         HR              Tax    5000
13        Bob         IT              Tax    6000
14    Charlie    Finance              Tax    5500
15      David         IT              Tax    5200
16        Eve         IT              Tax    5580
17      Frank         HR              Tax    6200

### TASK_10: Export the Data 

In [274]:
melted_df.to_csv('updated_dataset.csv', index =False)

In [277]:
'''Confirming that the cleaned dataset has be exported to csv file'''

import csv
with open('updated_dataset.csv','r') as file:
    read_file = csv.reader(file)

    for index, line in enumerate(read_file):
        if index == 0:
            print('Header')
            print(line)
            print('Data')
            '''Printing 10 records'''
        elif index == 11:
            break
        else:
            print(line)
        
            

Header
['Staff Name', 'Department', 'Salary Component', 'Amount']
Data
['Alice', 'HR', 'Staff Salary', '50000']
['Bob', 'IT', 'Staff Salary', '60000']
['Charlie', 'Finance', 'Staff Salary', '55000']
['David', 'IT', 'Staff Salary', '52000']
['Eve', 'IT', 'Staff Salary', '55800']
['Frank', 'HR', 'Staff Salary', '62000']
['Alice', 'HR', 'Net Salary', '45000']
['Bob', 'IT', 'Net Salary', '54000']
['Charlie', 'Finance', 'Net Salary', '49500']
['David', 'IT', 'Net Salary', '46800']


In [278]:
'''Exporting the melted dataframe to JSON format'''
'''This displays a dictionary showing:
1. list of columns of the dataframe
2. list of indexs for the dataframe
3. list of rows(records)'''
display(melted_df.to_json(orient= 'split'))

'{"columns":["Staff Name","Department","Salary Component","Amount"],"index":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],"data":[["Alice","HR","Staff Salary",50000],["Bob","IT","Staff Salary",60000],["Charlie","Finance","Staff Salary",55000],["David","IT","Staff Salary",52000],["Eve","IT","Staff Salary",55800],["Frank","HR","Staff Salary",62000],["Alice","HR","Net Salary",45000],["Bob","IT","Net Salary",54000],["Charlie","Finance","Net Salary",49500],["David","IT","Net Salary",46800],["Eve","IT","Net Salary",50220],["Frank","HR","Net Salary",55800],["Alice","HR","Tax",5000],["Bob","IT","Tax",6000],["Charlie","Finance","Tax",5500],["David","IT","Tax",5200],["Eve","IT","Tax",5580],["Frank","HR","Tax",6200]]}'